review message
ome/omero-cli-duplicate pull request #25
Opened 2024-02-27 17:30 UTC by jburel

Review ``dry run `` message
see #5

2024-02-28 10:25 UTC, pwalczysko commented
The message change in this PR is okay.
But I think you need to rebase on master to fix the failing test - @sbesson pushed some commits today to master, I have tried to rebase your branch on master and it fixed the tests, see https://github.com/pwalczysko/omero-cli-duplicate/actions/runs/8078799489

2024-02-28 10:26 UTC, pwalczysko requested changes
Fix the build (probably by rebasing on master)

2024-03-13 09:03 UTC, jburel commented
@pwalczysko build is now green

2024-03-13 10:33 UTC, pwalczysko commented on src/omero/plugins/duplicate.py
> +    # Report all the objects that  would have been duplicated by
```suggestion
    # Report all the objects that would have been duplicated by
```

2024-03-13 10:34 UTC, pwalczysko requested changes
one redundant whitespace found https://github.com/ome/omero-cli-duplicate/pull/25/files#r1522965832

2024-03-13 11:09 UTC, pwalczysko approved these changes

2024-11-21 13:58 UTC, merged